### ISSUE TITLE
repository does not exist

### ISSUE THREAD

**Issue by magick93** [hofstadter-io/hof#142]
Hi

I'm using `v0.6.8-beta.7` - installed using brew.

When I run `hof create github.com/hofstadter-io/hofmod-cli` I get

```
repository does not exist
```

**Comment by verdverm** [comment]
hmmm, I get a different error on linux

```
setting up...
loading remote creator
fetching creator dependencies
init'n generator
Errors while loading Cue entrypoints:  []
Creator.Create: field not allowed:
    ./creators/creator.cue:8:10
    ./creators/creator.cue:23:3
    ./creators/creator.cue:24:3
    ./creators/creator.cue:24:20
    ./cue.mod/pkg/github.com/hofstadter-io/hof/schema/create/create.cue:4:19
    ./cue.mod/pkg/github.com/hofstadter-io/hof/schema/gen/generator.cue:78:2
    ./hof.cue:8:12
```

Did you install on linux like your other issue, or is this Mac specific?

Things I will do:
- update `hofmod-cli` creator for new module files & format
- add test for this creator to github workflow
- try this out on real mac hardware

This is mostly an issue with `hofmod-cli`, I will link the issue there

**Comment by verdverm** [comment]
@magick93 can you try running this now?

```
hof create github.com/hofstadter-io/hofmod-cli@v0.8.2
```

**Comment by verdverm** [comment]
hmm, I may need to get a new beta out to fix this...

**Comment by magick93** [comment]
Hi @verdverm 

I tried `hof create github.com/hofstadter-io/hofmod-cli@v0.8.2` and it _looks_ better. This is the output:
```
setting up...
loading remote creator
fetching creator dependencies
init'n generator
Creating a new Go Cli
? What is your CLI named myhof
? Git repository github.com/user/repo
? Tell us a bit about it... learning to use hof
? Enable GoReleaser tooling Yes
? Enable self updating Yes
? Enable telemetry No
warning: creators/statics/ not found for , if you do not intend to use this directory, set 'Statics: []'
warning: creators/static/ not found for , if you do not intend to use this directory, set 'Statics: []'
warning: creators/partials/ not found for , if you do not intend to use this directory, set 'Partials: []'
Creator.Create.Args: field not allowed (and 1 more errors)
While loading generators
```

And there are no files created in the folder.

**Comment by magick93** [comment]
> Did you install on linux like your other issue, or is this Mac specific?

I'm Linux all the way.

**Comment by verdverm** [comment]
Yup, I think that error is CLI -> HOF -> CLI in cue deps, which shouldn't be happening.

I cannot figure out why it still thinks the Args is there, but apparently it should be and it is the `hof/schema/create` that should be updated. I recall what it is for now, need to document it

**Comment by magick93** [comment]
Thanks for looking into this.

Will there be a new release with the fix or do I not need to upgrade?

**Comment by verdverm** [comment]
@magick93 I released a new beta that should fix your two issues. Please reopen if you face issues.

Thanks for the reports!

````
hof create github.com/hofstadter-io/hofmod-cli@v0.8.3

# if you have git issues, try
rm -rf $HOME/.cache/hof/src
```
