### ISSUE TITLE
Errors while loading Cue entrypoints:  [example.cue]

### ISSUE THREAD

**Issue by magick93** [hofstadter-io/hof#143]
Hi

I'm trying to get familiar with the basics by following https://docs.hofstadter.io/first-example/setup/#bootstraping-your-geneartor

I ran the following commands:

1. `hof gen --init hof.io/docs/example` This resulted in:
```
Initializing: hof.io/docs/example in pkg example
To run the 'example' generator...
  $ hof gen example.cue -G example
```
2. I then ran `hof gen example.cue -G example`. And I got the following error:

```
Errors while loading Cue entrypoints:  [example.cue]
expected operand, found '&':
    ./example.cue:61:3
expected '}', found 'EOF':
    ./example.cue:68:3
```

## Version

```
Version:     v0.6.8-beta.7
Commit:      377035a06a97b6b7cb21089722eb3b0ff265e4ab

BuildDate:   2023-02-26T23:23:11Z
GoVersion:   go1.20.1
OS / Arch:   linux amd64
```

**Comment by verdverm** [comment]
This one looks like a CUE formatting bug, possibly known, there are a few similar issues with comments and formatting. I will
1. adjust the comments in the code hof generates
2. find / open a CUE issue for this
