### ISSUE TITLE
hof/fmt: add support for sql

### ISSUE THREAD

**Issue by magick93** [hofstadter-io/hof#149]
Hello

It would be great to have formatting support for sql (postgresql in particular).

**Comment by verdverm** [comment]
@magick93 thanks for the request, cannot believe I didn't add it already

we'll be using: https://github.com/un-ts/prettier

which, through deps, looks to support many SQL dialects. We'll have to figure out how to set you up to use the postgresql language, via the config on generator or file formatters

**Comment by verdverm** [comment]
fixed in #150
