### ISSUE TITLE
hof/gen: Test generators with podman

### ISSUE THREAD

**Issue by andrewhare** [hofstadter-io/hof#223]
Running `hof gen` with podman and `DOCKER_HOST` set to `"unix://$(podman machine inspect --format '{{.ConnectionInfo.PodmanSocket.Path}}')"` fails:

```terminal
Error response from daemon: failed to load image: payload does not match any of the supported image formats:
 * oci: initializing source oci:/var/tmp/api_load.tar2715591325:: open /var/tmp/api_load.tar2715591325/index.json: not a directory
 * oci-archive: creating temp directory: untarring file "/var/tmp/oci251356057": unexpected EOF
 * docker-archive: loading tar component manifest.json: unexpected EOF
 * dir: open /var/tmp/api_load.tar2715591325/manifest.json: not a directory
```

**Comment by verdverm** [comment]
we should probably also make sure we are compatible with containerd, runc, and other runtimes

**Comment by verdverm** [comment]
@andrewhare what did you do to work around this?

I recall you hit an error like this at one point:

```
hof gen init [hof.io/docs/example](http://hof.io/docs/example)
Initializing: [hof.io/docs/example](http://hof.io/docs/example) in pkg example
[github.com/hofstadter-io/hof@v0.6.8-rc.4](http://github.com/hofstadter-io/hof@v0.6.8-rc.4): cannot determine registry kind for: [github.com/hofstadter-io/hof](http://github.com/hofstadter-io/hof)
```

and had to do something with podman to get things working with hof?

**Comment by verdverm** [comment]
I'd at least like to not fail before the next release, seems like we probably watch an error and fail to quickly, if I recall the code correctly

**Comment by andrewhare** [comment]
@verdverm Unfortunately, the workaround was to switch to Docker.
