### ISSUE TITLE
TUI: enable a "demo" workflow: broken-CUE /cue-export-fails / fix-CUE / cue-export-passes

### ISSUE THREAD

**Issue by jpluscplusm** [hofstadter-io/hof#292]
## What feature would you like?

As per https://cuelang.slack.com/archives/CLT3ULF6C/p1693739094537959?thread_ts=1693600480.602179&channel=CLT3ULF6C&message_ts=1693739094.537959:

It'd be great if the TUI could enable a "showing off a demo" mode. 

## Is your feature request related to a problem you are experiencing? Please describe.

This'd be for the scenario where I'm recording or teaching, and:

- I have some broken CUE (file on disk, or just in memory; it doesn't really matter)
- I have a separate TUI window/tab/etc showing that a `cue export` (or whatever) is failing
- I fix the CUE (whether editing files on disk or twiddling them via the TUI is unimportant to /me/)
- the parallel `cue export` (or whatever) tab updates to show that the problem is fixed

I know this is already achievable  with tmux/etc, so this is definitely only a nice-to-have feature for hof!

## Describe the solution you'd like

I'd love a hof TUI that permitted live updates to output to be triggered by (or simply to reflect, with "acceptable" latency) changes to some CUE. 

## Describe alternatives you've considered

Tmux or separate terminal windows with a `watch` command.

Editing a file, backgrounding the editor, re-running the `cue` command. 

## Additional context

N/a

**Comment by verdverm** [comment]
This should be mostly implemented now, tracking some QoL stuff on top in #313
