### ISSUE TITLE
BUG: v0.6.10-rc.1 - feedback crashes

### ISSUE THREAD

**Issue by gedw99** [hofstadter-io/hof#396]
from a raw folder.

using v0.6.10-rc.1

hof feedback -h 
hof feedback 

both crash the program on a panic with

panic: unable to redefine 'I' shorthand in "feedback" flagset: it's already used for "issue" flag

**Comment by verdverm** [comment]
ug... wish cobra package caught these earlier than runtime of a specific command
(like validate the entire config, not just the one used...)
