### ISSUE TITLE
Unhelpful error message: exec json: exec: cmd run: exit status 1

### ISSUE THREAD

**Issue by metadatadriven** [hofstadter-io/hof#398]
### What version of `hof` are you using (`hof version`)?

<pre>
$ hof version
exec json: exec: cmd run: exit status 1

hof - the high code framework

Version:     v0.6.9
Commit:      7f04ae5477839ad5907b7fafe7b1052d48782a2c

BuildDate:   2024-06-07T07:06:17Z
GoVersion:   go1.21.10
CueVersion:  0.9.0
OS_Arch:     linux_amd64
ConfigDir:   /home/xxx/.config/hof
CacheDir:    /home/xxx/.cache/hof
Containers:   [ (client) |  (server)]

Author:      Hofstadter, Inc
License:     Apache-2.0
Homepage:    https://hofstadter.io
GitHub:      https://github.com/hofstadter-io/hof

$ go version
go version go1.21.6 linux/amd64
</pre>

### What did you do?

Installed hof on Windows 10 WSL2 following source install instructions
```sh
git clone https://github.com/hofstadter-io/hof && cd hof
git checkout v0.6.9
make hof
```

Then follow [the walkthrough](https://docs.hofstadter.io/the-walkthrough/) steps up to the [Generate the code](https://docs.hofstadter.io/the-walkthrough/simple-server/using/#generate-the-code) step

### What happened?

Executing the `hof gen` command resulted in an error
```sh
$ hof gen ./examples
exec json: exec: cmd run: exit status 1
```

It does not look like the command actually ran - there was no `./output` directory created.

The error message does not contain any meaningful information that I can use to debug and track down where the problem is.

### What did you expect to see?

Expect that either the `hof gen` command should work, or the error message should describe the problem so that the error can be fixed.

**Comment by metadatadriven** [comment]
Ok, so the cause seems to be that docker was not running!.. when I run Docker Desktop then the `hof gen ./examples` command runs without error and the `./output` directory is created as expected.

Suggest adding Docker dependency to the documentation, also a clearer error message would definitely help:)

**Comment by verdverm** [comment]
The installation page has a subline about the requirements, though these could be called out better (https://docs.hofstadter.io/install/)

I agree that error message is not helpful.

**Comment by verdverm** [comment]
improved error message in v0.6.10-rc.2
