### ISSUE TITLE
Use hof as code generator

### ISSUE THREAD

**Issue by rahul-thakoor** [hofstadter-io/hof#64]
Hello,

I would like to use hof to generate code using cuelang as the IDL.

Is it possible to provide an example on how to do this? The [tests](https://github.com/hofstadter-io/hof/tree/master/test/templates) indicate this should be possible

The goal is to define the datamodels/schemas in cuelang and use templates(preferably using mustache templating) to generate different target clients.

Any help is highly appreciated. Thanks :)

**Comment by verdverm** [comment]
Hi @rahul-thakoor 

You can follow the hof tool's design and code gen by

- starting here: https://github.com/hofstadter-io/hof/blob/master/hof.cue
- follow into the design directory
- checkout the hofmod-cli and hofmod-cuefig repos under this org
- run `hof gen` (it also supports flags for only generating subsets of design)

This is the most up to date and is run during my hof dev'n.

There is a single file example here: https://github.com/hofstadter-io/hof/blob/master/hof.cue with outdated Cue syntax. The tests are also on old syntax.

Once I get the new HLS scripting runtime put together I'm taking a long coding break to work on docs, examples, web sites, and much more. Stay tuned, also feel free to jump into gitter if you'd like to get help in chat mode.

Cheers!

**Comment by rahul-thakoor** [comment]
Thanks a lot.

**Comment by rahul-thakoor** [comment]
is this the right gitter https://gitter.im/hofstadter-io/hof#?

**Comment by verdverm** [comment]
Yes, I haven't been in there in a while, thought I would get notifications on mobile when someone wrote a message.

**Comment by verdverm** [comment]
@rahul-thakoor Finally got to prototyping a generator for servers and databases: https://github.com/hofstadter-io/hofmod-server

What do you think?

**Comment by verdverm** [comment]
Closing this as https://docs.hofstadter.io/getting-started/ is starting to take shape
